import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  formatDiagnosticCommand,
  validateLockfileText,
  validateRepository,
  validateWorkflowText,
} from "./verify-actions-lock.mjs";

const CHECKOUT_SHA = "3d3c42e5aac5ba805825da76410c181273ba90b1";
const CODEQL_SHA = "db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28";

function validLockfile({ workflow = ".github/workflows/ci.yml", pin = `actions/checkout@${CHECKOUT_SHA}` } = {}) {
  return `# This file is machine-generated by \`gh actions-lock\`.
version: 'v0.0.2'
workflows:
    '${workflow}':
        - '${pin}'
dependencies:
    '${pin}':
        ref: 'v7.0.1'
        commit: 'sha1-${CHECKOUT_SHA}'
        owner_id: 44036562
        repo_id: 197814629
`;
}

async function repositoryFixture(t, workflowText, lockfileText = validLockfile()) {
  const root = await mkdtemp(path.join(os.tmpdir(), "actions-lock-validator-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(path.join(root, ".github", "workflows"), { recursive: true });
  await writeFile(path.join(root, ".github", "workflows", "ci.yml"), workflowText);
  await writeFile(path.join(root, ".github", "workflows", "actions.lock"), lockfileText);
  return root;
}

test("accepts a canonical SHA-pinned lockfile", () => {
  const result = validateLockfileText(validLockfile());
  assert.deepEqual(result.diagnostics, []);
});

test("rejects the exact symbolic-ref class introduced by PR #19", () => {
  const historicalFragment = `# This file is machine-generated by \`gh actions-lock\`.
version: 'v0.0.2'
workflows:
    '.github/workflows/scorecard.yml':
        - 'actions/checkout@v7.0.1'
        - 'github/codeql-action@v4.37.8'
dependencies:
    'actions/checkout@v7.0.1':
        ref: 'v7.0.1'
        commit: 'sha1-${CHECKOUT_SHA}'
        owner_id: 44036562
        repo_id: 197814629
    'github/codeql-action@v4.37.8':
        ref: 'v4.37.8'
        commit: 'sha1-${CODEQL_SHA}'
        owner_id: 9919
        repo_id: 259445878
`;

  const result = validateLockfileText(historicalFragment);
  assert.equal(result.diagnostics.some((item) => item.message.includes("symbolic ref")), true);
  assert.equal(result.diagnostics.length >= 4, true);
});

test("rejects a dependency whose metadata commit does not match its key", () => {
  const lockfile = validLockfile().replace(`sha1-${CHECKOUT_SHA}`, `sha1-${CODEQL_SHA}`);
  const result = validateLockfileText(lockfile);
  assert.match(result.diagnostics[0].message, /commit must be/);
});

test("rejects unsupported 64-character action object identifiers", () => {
  const sha256 = "a".repeat(64);
  const result = validateLockfileText(validLockfile({ pin: `actions/checkout@${sha256}` }));
  assert.equal(result.diagnostics.some((item) => item.message.includes("full commit SHA")), true);
});

test("rejects missing and invalid dependency metadata", () => {
  const lockfile = validLockfile()
    .replace("        ref: 'v7.0.1'\n", "")
    .replace("        owner_id: 44036562", "        owner_id: 0");
  const result = validateLockfileText(lockfile);
  assert.equal(result.diagnostics.some((item) => item.message.includes("has no ref")), true);
  assert.equal(result.diagnostics.some((item) => item.message.includes("positive decimal integer")), true);
});

test("rejects a symbolic remote uses reference even when the lockfile is canonical", () => {
  const result = validateWorkflowText("jobs:\n  test:\n    uses: actions/checkout@v7\n", ".github/workflows/ci.yml");
  assert.equal(result.diagnostics.length, 1);
  assert.match(result.diagnostics[0].message, /symbolic ref/);
});

test("rejects an adversarial malformed action path without ambiguous parsing", () => {
  const malformed = `${"-/-/".repeat(10_000)}main`;
  const result = validateWorkflowText(`jobs:\n  test:\n    uses: ${malformed}\n`, ".github/workflows/ci.yml");
  assert.equal(result.diagnostics.length, 1);
  assert.match(result.diagnostics[0].message, /invalid action pin/);
});

test("accepts local, self-repository and container references without lock entries", () => {
  const result = validateWorkflowText(
    "jobs:\n  test:\n    steps:\n      - uses: ./action\n      - uses: $/action\n      - uses: docker://alpine:3.23\n",
    ".github/workflows/ci.yml",
  );
  assert.deepEqual(result, { diagnostics: [], remotePins: [] });
});

test("does not treat shell text inside a block scalar as workflow uses", () => {
  const result = validateWorkflowText(
    "jobs:\n  test:\n    steps:\n      - run: |\n          uses: actions/checkout@main\n          printf 'data only'\n",
    ".github/workflows/ci.yml",
  );
  assert.deepEqual(result, { diagnostics: [], remotePins: [] });
});

test("does not treat ordinary env or input keys named uses as action invocations", () => {
  const result = validateWorkflowText(
    `env:
  uses: production
jobs:
  test:
    env:
      uses: staging
    steps:
      - name: Exercise an ordinary input
        uses: actions/checkout@${CHECKOUT_SHA}
        with:
          uses: nested-input
      - name: Exercise a step environment
        env:
          uses: nested-environment
        run: printf 'safe\\n'
`,
    ".github/workflows/ci.yml",
  );
  assert.deepEqual(result.diagnostics, []);
  assert.deepEqual(result.remotePins.map((pin) => pin.raw), [`actions/checkout@${CHECKOUT_SHA}`]);
});

test("the unprivileged trigger covers pull requests and merge groups without filters", async () => {
  const trigger = await readFile(
    new URL("../.github/workflows/actions-lock-trigger.yml", import.meta.url),
    "utf8",
  );
  assert.match(trigger, /^\s{2}pull_request:\s*$/m);
  assert.match(trigger, /^\s{2}merge_group:\s*$/m);
  assert.match(trigger, /^permissions: \{\}\s*$/m);
  assert.doesNotMatch(trigger, /^\s+- uses:/m);
  const eventBlock = trigger.match(/on:\s*\n([\s\S]*?)\npermissions:/)?.[1] ?? "";
  assert.doesNotMatch(eventBlock, /^\s+(branches|branches-ignore|paths|paths-ignore|types):/m);
});

test("the trusted validator preserves every privileged trust-boundary invariant", async () => {
  const validator = await readFile(
    new URL("../.github/workflows/actions-lock-validate.yml", import.meta.url),
    "utf8",
  );
  assert.match(validator, /\^\(pull_request\|merge_group\)\$/);
  assert.match(validator, /^\s{6}contents: read\b/m);
  assert.match(validator, /^\s{6}statuses: write\b/m);
  assert.match(
    validator,
    /^\s{10}HEAD_REPOSITORY: \$\{\{ github\.event\.workflow_run\.head_repository\.full_name \}\}\s*$/m,
  );
  assert.match(
    validator,
    /^\s{10}HEAD_SHA: \$\{\{ github\.event\.workflow_run\.head_sha \}\}\s*$/m,
  );
  assert.match(
    validator,
    /^\s{10}TRIGGER_EVENT: \$\{\{ github\.event\.workflow_run\.event \}\}\s*$/m,
  );
  assert.match(validator, /^\s{10}TRUSTED_BASE_SHA: \$\{\{ github\.sha \}\}\s*$/m);
  assert.match(validator, /repos\/\$\{BASE_REPOSITORY\}\/statuses\/\$\{HEAD_SHA\}/);
  assert.match(
    validator,
    /repos\/\$\{BASE_REPOSITORY\}\/contents\/\$\{validator_path\}\?ref=\$\{TRUSTED_BASE_SHA\}/,
  );
  assert.match(validator, /find -P "\$\{snapshot_root\}" -type l -print -quit/);
  assert.match(
    validator,
    /readonly lock_asset_sha256='4181ec1da5408b34b9a542a7ee5c6ce3a4d6ac815c7d0206a00ceca8a817f4e3'/,
  );
});

test("rejects an invalid self-repository reference", () => {
  const result = validateWorkflowText("jobs:\n  test:\n    uses: $/action@main\n", ".github/workflows/ci.yml");
  assert.match(result.diagnostics[0].message, /must not contain @ref/);
});

test("escapes untrusted file names in GitHub workflow commands", () => {
  assert.equal(
    formatDiagnosticCommand({
      file: ".github/workflows/evil%,:\n.yml",
      line: 7,
      message: "bad%\r\nvalue",
    }),
    "::error file=.github/workflows/evil%25%2C%3A%0A.yml,line=7::bad%25%0D%0Avalue",
  );
});

test("repository validation requires exact agreement between workflows and lockfile", async (t) => {
  const root = await repositoryFixture(
    t,
    `jobs:\n  test:\n    steps:\n      - uses: actions/checkout@${CHECKOUT_SHA}\n`,
  );
  assert.deepEqual((await validateRepository(root)).diagnostics, []);

  await writeFile(
    path.join(root, ".github", "workflows", "ci.yml"),
    `jobs:\n  test:\n    steps:\n      - uses: github/codeql-action/analyze@${CODEQL_SHA}\n`,
  );
  const result = await validateRepository(root);
  assert.equal(result.diagnostics.some((item) => item.message.includes("absent from actions.lock")), true);
  assert.equal(result.diagnostics.some((item) => item.message.includes("stale workflow dependency")), true);
});

test("repository validation fails closed when the lockfile is missing", async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), "actions-lock-validator-missing-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(path.join(root, ".github", "workflows"), { recursive: true });
  await assert.rejects(validateRepository(root), /ENOENT/);
});
