name: Zizmor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types:
      - checks_requested
  schedule:
    - cron: "43 5 * * 1"
  workflow_dispatch:

permissions: write-all

concurrency:
  group: zizmor-${{ github.ref }}
  queue: max
  cancel-in-progress: false

jobs:
  zizmor:
    name: Run zizmor
    permissions: write-all
    uses: LCV-Ideas-Software/.github/.github/workflows/zizmor.yml@97627f2a1d70e59d6868e0d682c988d05b63e88c # zizmor/v2.2.0
