# This workflow is managed by gh actions-lock.

name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

permissions: {}

concurrency:
  group: zizmor-${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      security-events: write # Upload Zizmor results to code scanning.
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99 # v0.6.3
        with:
          version: "1.29.0"
