name: Zizmor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types:
      - checks_requested
  schedule:
    - cron: "43 5 * * 1"
  workflow_dispatch:

permissions: write-all

concurrency:
  group: zizmor-${{ github.ref }}
  queue: max
  cancel-in-progress: false

jobs:
  zizmor:
    name: Run zizmor
    permissions: write-all
    uses: LCV-Ideas-Software/.github/.github/workflows/zizmor.yml@4058fad11eca7c2eb4e9296108667ef6199a6356 # zizmor/v2.0.0
